### ISSUE TITLE
Druid not starting tasks upon Supervisor submit

### ISSUE THREAD

**Issue by OMR5221** [Fokko/divolte-kafka-druid-superset#14]
I do not find that Druid is starting any tasks after the divolte-clickstream supervisor-spec.json file has been submitted.
The supervisor does go into the running state, but no tasks seem to be generated.
I tried other supervisor spec files as well such as the wikipedia streaming spec json provided here: https://druid.apache.org/docs//0.15.1-incubating/tutorials/tutorial-kafka.html
but still no tasks.

**Comment by itamarg365** [comment]
same here.
following...

**Comment by OMR5221** [comment]
I have been experimenting and find that this seems to work if Kafka is using the Zookeeper instance running in the Druid container.
I have no idea why though.
I am building the image for the druid container manually using the github link: https://github.com/Fokko/docker-druid

**Comment by OMR5221** [comment]
Was able to get running locally but had to make several changes to do so.
Definitely not best practice for container deployment, but worked for me just to get an idea of how these technologies might work together: https://github.com/OMR5221/docker-divolte-kafka-druid-superset-redux

**Comment by carstengithub** [comment]
see my comment at [https://github.com/Fokko/divolte-kafka-druid-superset/issues/15](url)
