### ISSUE TITLE
zookeeper version is not available

### ISSUE THREAD

**Issue by hughimr** [Fokko/divolte-kafka-druid-superset#2]
the path of zookeeper 3.4.9 source file is not available in druid/Dockerfile .version 3.4.10 is ok

**Comment by Fokko** [comment]
Thanks @hughimr, I've just pushed a fix. Zookeeper deprecates the old versions of zookeeper, and removes them from the repository. Therefore it isn't available anymore. I've upgraded to 3.4.11 right away. Cheers
